name: Java CI with Gradle

on:
  push:
    branches: [ master, release ]
  pull_request:
    branches: [ master, release ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build with Gradle
      run: ./gradlew build    

  publish:
    needs: build
    runs-on: ubuntu-latest
    steps:
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build with Gradle
    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:          
        username: ${{ secrets.DOCKER_USER }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    - name: Build and push Docker images
      run: ./gradlew dockerPush
